baseURL = "http://blog.wille-zone.de/"
languageCode = "de-DE"
title = "Boris Wilhelms"
theme = "hugo-theme-minos"

relativeURLs = true
disableKinds = [""]

[[menu.main]]
    name = "About me"
    url = "/about"

[Params]
    Author = "Boris Wilhelms"