baseURL = "http://blog.wille-zone.de/"
languageCode = "de-DE"
title = "Boris Wilhelms"
theme = "hugo-theme-minos"

relativeURLs = true
disableKinds = [""]

googleAnalytics = "UA-98632338-1"

[[menu.main]]
    name = "About me"
    url = "/about"

[Params]
    Author = "Boris Wilhelms"

[blackfriday]
    hrefTargetBlank = true